on:
  push:
    branches:
      - main
      - master
      - develop
    workflow_dispatch:
name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.0'
      - run: flutter pub get
      - run: flutter build web
      - run: |
          rd /s/q ./docs/*
          cp -r ./build/web/* ./docs/
          git status
          git add .
          git config --global user.email "sm8967724231@gmail.com"
          git config --global user.name "Rey"
          git commit -m "Auto updating"
          git fetch origin main
          git push origin HEAD:main
